### ISSUE TITLE
DateOrDateTimeDataType_Shape doesn't seem to work

### ISSUE THREAD

**Issue by jimjyang** [ISAITB/validator-resources-bregdcat-ap#4]
The following simple example datasets got SUCCESS from the BRegDCAT-AP validator at https://www.itb.ec.europa.eu/shacl/bregdcat-ap/upload, although the datatypes for `dct:modified` are deliberately wrong. 
```
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <https://examples.com/> .

:ds1 a dcat:Dataset ;
  dct:title "t" ; # mandatory
  dct:identifier "i" ; # mandatory
  dct:description "d" ; # mandatory
  dct:modified "2021-01-01" ; # wrong datatype but no violation, should be typed as xsd:date
  .

:ds2 a dcat:Dataset ;
  dct:title "t" ; # mandatory
  dct:identifier "i" ; # mandatory
  dct:description "d" ; # mandatory
  dct:modified "2"^^xsd:integer ; # wrong datatype but no violation
  .
```

**Comment by agmangas** [comment]
It seems that the issue originates from not using the appropriate constraint components in the BRegDCAT-AP SHACL shapes.

Currently, in some places we use the `sh:shape` constraint component to point to the reusable shape that must be used to validate a property in a `sh:NodeShape`. However `sh:shape` does not seem to be an [existing constraint component](https://www.w3.org/TR/shacl/#core-components). The following code block shows an example:

```
:Dataset_Shape
    a sh:NodeShape ;
    sh:name "Dataset"@en ;
    # Other properties removed for clarity
    sh:property [
        sh:maxCount 1 ;
        sh:path dct:modified ;
        sh:severity sh:Violation ;
        sh:shape :DateOrDateTimeDataType_Shape
    ] ;
    sh:targetClass dcat:Dataset .
    
:DateOrDateTimeDataType_Shape
    a sh:NodeShape ;
    rdfs:comment "Date time date disjunction shape checks that a datatype property receives a date or a dateTime literal" ;
    rdfs:label "Date time date disjunction" ;
    sh:message "The values must be data typed as either xsd:date or xsd:dateTime" ;
    sh:or ([
            sh:datatype xsd:date
        ]
        [
            sh:datatype xsd:dateTime
        ]
    ) .
```

I'd say that the solution is to use [`sh:node`](https://www.w3.org/TR/shacl/#NodeConstraintComponent) instead of `sh:shape`. This results in the expected validation report:

```
[ a            sh:ValidationReport ;
  sh:conforms  false ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  <https://examples.com/ds2> ;
                 sh:resultMessage              "Value does not have shape :DateOrDateTimeDataType_Shape" ;
                 sh:resultPath                 dct:modified ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:NodeConstraintComponent ;
                 sh:sourceShape                _:b0 ;
                 sh:value                      2
               ] ;
  sh:result    [ a                             sh:ValidationResult ;
                 sh:focusNode                  <https://examples.com/ds1> ;
                 sh:resultMessage              "Value does not have shape :DateOrDateTimeDataType_Shape" ;
                 sh:resultPath                 dct:modified ;
                 sh:resultSeverity             sh:Violation ;
                 sh:sourceConstraintComponent  sh:NodeConstraintComponent ;
                 sh:sourceShape                _:b0 ;
                 sh:value                      "2021-01-01"
               ]
] .
```

I'll upload a fix shortly.

**Comment by jimjyang** [comment]
Thanks, @agmangas, for the fix, which works! 

A little detail: the `sh:message "The values must be data typed as either xsd:date or xsd:dateTime"` i the shape `:DateOrDateTimeDataType_Shape` doesn't seem to be used, instead I got the "default" violation message `Value does not have shape :DateOrDateTimeDataType_Shape` (which doesn't tell much). Any fix for that?

**Comment by agmangas** [comment]
Thank you! You're right, I'll look into it 😄

**Comment by agmangas** [comment]
It seems that messages that are declared using `sh:message` on nested shapes (i.e. referenced using `sh:node`) are not displayed as the `sh:resultMessage` of validation results. SHACL interprets them as _child_ messages, and instead shows the _parent_ message, that is, the default message for a nested shape violation.

These _child_ messages should appear in another node referenced by [`sh:detail`](https://www.w3.org/TR/shacl/#results-detail) in the validation result. However, this does not seem to be the case with the SHACL implementation in the ISA ITB nor in the [other ones](https://shacl-playground.zazuko.com/) that I've tested.

Adding the `sh:message` to the property works, although I'm afraid that this is very verbose and would force us to duplicate messages all over the shapes 😞

**Comment by jimjyang** [comment]
> These _child_ messages should appear in another node referenced by [`sh:detail`](https://www.w3.org/TR/shacl/#results-detail) in the validation result. However, this does not seem to be the case with the SHACL implementation in the ISA ITB nor in the [other ones](https://shacl-playground.zazuko.com/) that I've tested.

😞

> Adding the `sh:message` to the property works, although I'm afraid that this is very verbose and would force us to duplicate messages all over the shapes 😞

Agreed. 

So we have to live without a more precise sh:message than the default one, till we (=you) find a suitable solution. 

Thanks anyway for trying!

**Comment by jimjyang** [comment]
@agmangas 

Sorry to bother you with this closed issue again, but I did a little test using the way that [CPSV-AP](https://github.com/catalogue-of-services-isa/CPSV-AP/tree/master/releases/2.2.1) is using (`sh:PropertyShape`) and the more precise sh:message from the PropertyShape did show up. Another advantage I think, is that "reusable properties" are specified only once. I have not tested thoroughly so I don't know if there are any "unwanted side effects". 

It might though require quite a lot of work to "convert" the current BRegDCAT-AP-shacl to the "CPSV-AP-way" (without automatic tool support).

**Comment by agmangas** [comment]
Thanks @jimjyang! I've created a new _enhancement_ issue to reflect this 😄
