### ISSUE TITLE
Using https in URLs to EU's controlled vocabularies results in violation

### ISSUE THREAD

**Issue by jimjyang** [ISAITB/validator-resources-bregdcat-ap#5]
The Publications Office has published (at least some of, if not all) the controlled vocabularies using https-protocol (in addition to http). 

However, the following simple example with https resulted in violation from the [BregDCAT-AP validator](https://www.itb.ec.europa.eu/shacl/bregdcat-ap/upload): 
```
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix : <https://examples.com/> .

:ds1 a dcat:Distribution ;
  dcat:accessURL <> ; # mandatory
  dct:format <https://publications.europa.eu/resource/authority/file-type/GDB> ; # https istedenfor http
  .
```

Although the PDF version of BRegDCAT-AP does say http and http only (I will raise an Issue suggesting to update this), the shacl should allow https. 

I have not checked, but I believe that this comment applies to all places in shacl where controlled vocabularies from Publications Office are referred to, currently using http.

**Comment by agmangas** [comment]
Commit https://github.com/ISAITB/validator-resources-bregdcat-ap/commit/01d1c2c151e645923f36c5f45856764905a518cc addresses this issue.  However, I'm not entirely happy with the result, as the solution that I came up with is really verbose 😅   

Suggestions to improve code quality would be greatly appreciated.

The following example uses both HTTP and HTTPS URLs, as well as an additional `skos:inScheme` value outside the controlled vocabulary. It now passes validation:

```
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix : <https://examples.com/> .

:ds1 
  a dcat:Distribution ;
  dcat:accessURL <> ;
  dct:format <https://publications.europa.eu/resource/authority/file-type/GDB> .

:ds2 
  a dcat:Distribution ;
  dcat:accessURL <> ;
  dct:format <http://publications.europa.eu/resource/authority/file-type/GEOJSON> .

<https://publications.europa.eu/resource/authority/file-type/GDB>
  a dct:MediaTypeOrExtent ;
  skos:inScheme :anotherScheme ;
  skos:inScheme <https://publications.europa.eu/resource/authority/file-type> .

<http://publications.europa.eu/resource/authority/file-type/GEOJSON>
  a dct:MediaTypeOrExtent ;
  skos:inScheme <http://publications.europa.eu/resource/authority/file-type> .
```
